---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_condaenv("pydatafaker")
```

# PyDataFaker

A python package to create fake data with relationships between tables.

Creating fake data can be useful for many different applications. Python already has a great package for creating fake data called Faker [https://faker.readthedocs.io/en/master/](https://faker.readthedocs.io/en/master/). Faker is great for creating individual fake units of data, but it can be time consuming to create more complicated fake data that is actually related to one another.

Imagine you are developing a new enterprise resource planning (ERP) software to challenge SAP. You may need to create some fake data to test your application. You will need an invoice table, a vendor listing, purchase order table, and more. PyDataFaker allows your to quickly create these tables and generates relationships between them!

PyDataFaker is currently under development. At this time it is possible to create the following entities:

- Business: create a fake business with common ERP like tables

More entities are currently being developed. If you  have any ideas of additional entities that should be included please submit an issue here: [https://github.com/SamEdwardes/pydatafaker/issues](https://github.com/SamEdwardes/pydatafaker/issues).

## Table of contents

- [Installation](#installation)
- [Documentation](#documentation)
- [Usage](#usage)
- [Contributing](#contributing)
- [Credits](#credits)
- [Reminders for developers](#reminders-for-developers)

## Installation

```bash
pip install pydatafaker
```

## Documentation

Documentation can be found on...

> TODO: update read the docs

## Usage

### Business

Generate fake business data that could be used to populate an ERP tool.

```{python}
import pandas as pd
from pydatafaker import business
biz =  business.create_business()
```

`business.create_business()` returns a dictionary containing all of the related tables.

```{python}
biz.keys()
```

Each value inside the dictionary contains a Pandas DataFrame.

```{python}
biz['invoice_summary_table']
```

Tables can be joined together to add additional details.

```{python}
invoice_summary = biz['invoice_summary_table']
vendors = biz['vendor_table']

pd.merge(invoice_summary, vendors, how='left', on='vendor_id')
```

## Contributing

Please see [docs/source/contributing.rst](docs/source/contributing.rst).

## Credits

Developed by Sam Edwardes.
