# name: deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.7
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.7
#     - name: Install dependencies
#       run: |
#         pip install poetry
#         poetry install
#     - name: Test with pytest
#       run: poetry run pytest
#       - name: checkout
#       uses: actions/checkout@master
#     - name: Push package version changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#     - name: Get release tag version from package version
#       run: |
#         echo ::set-output name=release_tag::$(grep "version" */__init__.py | cut -d "'" -f 2 | cut -d '"' -f 2)
#       id: release
#     - name: Create Release with new version
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ steps.release.outputs.release_tag }}
#         release_name: ${{ steps.release.outputs.release_tag }}
#         draft: false
#         prerelease: false
#     - name: Build package and publish to PyPI
#     env:
#         PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }} 
#         PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#     run: |
#         poetry build
#         poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD


        